name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [win-x86,win-x64,win-arm64,linux-x64,linux-arm64,osx-x64]
        include:
          - target: win-x86
            platform: win
            architecture: x86
          - target: win-x64
            platform: win
            architecture: x64
          - target: win-arm64
            platform: win
            architecture: arm64
          - target: linux-x64
            platform: linux
            architecture: x64
          - target: linux-arm64
            platform: linux
            architecture: arm64
          - target: osx-x64
            platform: osx
            architecture: x64
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build CLI utilities
        shell: pwsh
        run: |
          msbuild /m /t:restore,KDS /p:Platform=${{ matrix.architecture }} /p:RuntimeIdentifier=${{ matrix.platform }}-${{ matrix.architecture }} /p:Configuration=Release KDS.sln
